import { writeFileSync } from "node:fs";
import { Resvg } from "@resvg/resvg-js";
import { LOGO_SYMBOLS } from "../src/logo-symbols";

/**
 * 심볼별 "실제 잉크 bbox" 표를 구워 `src/symbols/ink.generated.ts` 에 쓴다.
 *
 * 심볼 path 는 24 또는 100 그리드 위에 그려져 있지만 그리드를 꽉 채우지 않는다
 * (lucide 아이콘은 보통 2px 여백, flame 은 세로로 17/24 만 씀). 그래서 viewBox
 * 기준으로 크기를 맞추면 심볼마다 시각적 크기가 들쭉날쭉해진다.
 *
 * path 수식으로 bbox 를 구하려면 베지어·호 처리가 필요해서, 대신 실제로 한 번
 * 렌더한 뒤 알파 채널을 훑어 잉크 범위를 잰다. 정확하고 stroke 두께도 자동 반영.
 *
 * 실행: npm run bbox   (심볼 svg 를 추가/수정한 뒤에만 다시 돌리면 된다)
 */

const PX = 256;
const ALPHA_MIN = 8; // 안티에일리어싱 꼬리 무시

type Sym = typeof LOGO_SYMBOLS[number];

function symbolOnlySvg(sym: Sym): string {
  const vb = sym.vb ?? 100;
  const attrs = sym.stroke
    ? `fill="none" stroke="#000" stroke-width="${sym.strokeWidth ?? 2}" stroke-linecap="round" stroke-linejoin="round"`
    : `fill="#000"${sym.fillRule ? ` fill-rule="${sym.fillRule}"` : ""}`;
  const dList = Array.isArray(sym.d) ? sym.d : [sym.d as string];
  const paths = dList.map((d) => `<path d="${d}" ${attrs}/>`).join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${vb}" height="${vb}" viewBox="0 0 ${vb} ${vb}">${paths}</svg>`;
}

/** 알파 > 0 인 픽셀의 범위를 viewBox 대비 0~1 로 반환. */
function inkBox(sym: Sym): [number, number, number, number] | null {
  if (!sym.d) return null;

  const rendered = new Resvg(symbolOnlySvg(sym), { fitTo: { mode: "width", value: PX } }).render();
  const rgba = rendered.pixels;
  const w = rendered.width, h = rendered.height;

  let x0 = w, y0 = h, x1 = -1, y1 = -1;
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      if (rgba[(y * w + x) * 4 + 3] <= ALPHA_MIN) continue;
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
    }
  }
  if (x1 < 0) return null;
  return [x0 / w, y0 / h, (x1 + 1) / w, (y1 + 1) / h]; // +1: 끝 픽셀 포함
}

const rows: string[] = [];
const skipped: string[] = [];
for (const sym of LOGO_SYMBOLS) {
  const box = inkBox(sym);
  if (!box) { skipped.push(sym.id); continue; }
  rows.push(`  ${JSON.stringify(sym.id)}: [${box.map((n) => n.toFixed(4)).join(", ")}],`);
}

const out = `/* AUTO-GENERATED by scripts/gen-symbol-bbox.ts — 직접 수정하지 말 것. \`npm run bbox\` 로 재생성. */

/** 심볼별 잉크 bbox [x0, y0, x1, y1], viewBox 대비 0~1 비율. */
export const SYMBOL_INK: Record<string, [number, number, number, number]> = {
${rows.join("\n")}
};
`;

writeFileSync(new URL("../src/symbols/ink.generated.ts", import.meta.url), out);
console.log(`ink bbox: ${rows.length} symbols written, skipped ${skipped.length} (${skipped.join(",") || "none"})`);
